export const GET_POSTS = "GET_POSTS";
export const FETCH_POSTS = "FETCH_POSTS";
export const FETCH_POST = "FETCH_POST";
export const FETCH_POSTS_FOR_CATEGORY = "FETCH_POST_FOR_CATEGORY";
export const FETCH_POSTS_FOR_CATEGORY_FULFILLED =
  "FETCH_POST_FOR_CATEGORY_FULFILLED";
export const ADD_POST = "ADD_POST";
export const UPDATE_POST = "UPDATE_POST";
export const VOTE_ON_POST = "VOTE_ON_POST";
export const UP_VOTE_POST = "UP_VOTE_POST";
export const DOWN_VOTE_POST = "DOWN_VOTE_POST";

export const FETCH_COMMENTS_FOR_POST = "FETCH_COMMENTS_FOR_POST";
export const FETCH_COMMENT = "FETCH_COMMENT";
export const POST_COMMENT = "POST_COMMENT";
export const VOTE_ON_COMMENT = "VOTE_ON_COMMENT";
export const UP_VOTE_COMMENT = "UP_VOTE_COMMENT";
export const DOWN_VOTE_COMMENT = "DOWN_VOTE_COMMENT";
export const UPDATE_COMMENT = "UPDATE_COMMENT";

export const SORT_POSTS = "SORT_POSTS";
export const SORT_COMMENTS = "SORT_COMMENTS";

export const START_EDITING_COMMENT = "START_EDITING_COMMENT";
export const STOP_EDITING_COMMENT = "STOP_EDITING_COMMENT";

export const FETCH_CATEGORIES = "FETCH_CATEGORIES";
export const FETCH_CATEGORIES_FULFILLED = "FETCH_CATEGORIES_FULFILLED";

export const FETCH_ALL_POSTS_FULFILLED = "FETCH_ALL_POSTS_FULFILLED";
export const FETCH_ALL_POSTS = "FETCH_ALL_POSTS";

export const FETCH_POST_FULFILLED = "FETCH_POST_FULFILLED";

export const SET_CURRENT_POST = "SET_CURRENT_POST";

export const EDIT_POST = "EDIT_POST";
export const EDIT_POST_FULFILLED = "EDIT_POST_FULFILLED";

export const CREATE_POST = "CREATE_POST";
export const CREATE_POST_FULFILLED = "CREATE_POST_FULFILLED";

export const CHANGE_ROUTE = "CHANGE_ROUTE";
export const GET_ROUTE = "GET_ROUTE";

export const VOTE_POST = "VOTE_POST";
export const VOTE_POST_FULFILLED = "VOTE_POST_FULFILLED";

export const VOTE_COMMENT = "VOTE_COMMENT";
export const VOTE_COMMENT_FULFILLED = "VOTE_COMMENT_FULFILLED";

export const FETCH_ALL_COMMENTS = "FETCH_ALL_COMMENTS";
export const FETCH_ALL_COMMENTS_FULFILLED = "FETCH_ALL_COMMENTS_FULFILLED";

export const CHANGE_SORT = "CHANGE_SORT";
export const CHANGE_SORT_FULFILLED = "CHANGE_SORT_FULFILLED";

export const DELETE_POST = "DELETE_POST";
export const DELETE_POST_FULFILLED = "DELETE_POST_FULFILLED";

export const DELETE_COMMENT = "DELETE_COMMENT";
export const DELETE_COMMENT_FULFILLED = "DELETE_COMMENT_FULFILLED";

export const SET_CURRENT_COMMENT = "SET_CURRENT_COMMENT";

export const EDIT_COMMENT = "EDIT_COMMENT";
export const EDIT_COMMENT_FULFILLED = "EDIT_COMMENT_FULFILLED";

export const ADD_COMMENT = "ADD_COMMENT";
export const ADD_COMMENT_FULFILLED = "ADD_COMMENT_FULFILLED";

export const SET_ADD_NEW_COMMENT_MODE = "SET_ADD_NEW_COMMENT_MODE";
